name: Build and Push to Docker Hub

on:
  push:
    branches: [ master ]  # or 'master' if you're using that

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t nadun20001224/simple-inventory:latest .

    - name: Push Docker image
      run: |
        docker push nadun20001224/simple-inventory:latest
